export const currencyByRupee: Currency[] = [
    {
        name: 'DOLLAR',
        value: 0.01227,
        flag: '🇺🇸',
        symbol: '$',
    },
    {
        name: 'EURO',
        value: 0.01126,
        flag: '🇪🇺',
        symbol: '€',
    },
    {
        name: 'POUND',
        value: 0.00992,
        flag: '🇬🇧',
        symbol: '£',
    },
    {
        name: 'RUBEL',
        value: 0.8504,
        flag: '🇷🇺',
        symbol: '₽',
    },
    {
        name: 'AUS DOLLAR',
        value: 0.01733,
        flag: '🇦🇺',
        symbol: 'A$',
    },
    {
        name: 'CAN DOLLAR',
        value: 0.01646,
        flag: '🇨🇦',
        symbol: 'C$',
    },
    {
        name: 'YEN',
        value: 1.5909,
        flag: '🇯🇵',
        symbol: '¥',
    },
    {
        name: 'DINAR',
        value: 0.00374,
        flag: '🇰🇼',
        symbol: 'KD',
    },
    {
        name: 'BITCOIN',
        value: 0.00000054,
        flag: '🎰',
        symbol: '₿',
    },
    {
        name: 'SWISS FRANC',
        value: 0.01112,
        flag: '🇨🇭',
        symbol: 'CHF',
    },
    {
        name: 'CHINESE YUAN',
        value: 0.08355,
        flag: '🇨🇳',
        symbol: '¥',
    },
    {
        name: 'HONG KONG DOLLAR',
        value: 0.09544,
        flag: '🇭🇰',
        symbol: 'HK$',
    },
    {
        name: 'NEW ZEALAND DOLLAR',
        value: 0.01966,
        flag: '🇳🇿',
        symbol: 'NZ$',
    },
    {
        name: 'SWEDISH KRONA',
        value: 0.00620,
        flag: '🇸🇪',
        symbol: 'kr',
    },
    {
        name: 'SOUTH KOREAN WON',
        value: 15.88,
        flag: '🇰🇷',
        symbol: '₩',
    },
    {
        name: 'SINGAPORE DOLLAR',
        value: 0.01639,
        flag: '🇸🇬',
        symbol: 'S$',
    },
    {
        name: 'NORWEGIAN KRONE',
        value: 0.00824,
        flag: '🇳🇴',
        symbol: 'kr',
    },
    {
        name: 'MEXICAN PESO',
        value: 0.2287,
        flag: '🇲🇽',
        symbol: '$',
    },
    {
        name: 'SOUTH AFRICAN RAND',
        value: 0.01828,
        flag: '🇿🇦',
        symbol: 'R',
    },
    {
        name: 'TURKISH LIRA',
        value: 0.2311,
        flag: '🇹🇷',
        symbol: '₺',
    },
    {
        name: 'BRAZILIAN REAL',
        value: 0.06346,
        flag: '🇧🇷',
        symbol: 'R$',
    },
    {
        name: 'TAIWAN NEW DOLLAR',
        value: 0.3729,
        flag: '🇹🇼',
        symbol: 'NT$',
    },
    {
        name: 'DANISH KRONE',
        value: 0.085,
        flag: '🇩🇰',
        symbol: 'kr',
    },
    {
        name: 'POLISH ZLOTY',
        value: 0.0536,
        flag: '🇵🇱',
        symbol: 'zł',
    },
    {
        name: 'THAI BAHT',
        value: 0.4214,
        flag: '🇹🇭',
        symbol: '฿',
    },
    {
        name: 'INDONESIAN RUPIAH',
        value: 186.57,
        flag: '🇮🇩',
        symbol: 'Rp',
    },
    {
        name: 'MALAYSIAN RINGGIT',
        value: 0.0546,
        flag: '🇲🇾',
        symbol: 'RM',
    },
    {
        name: 'PHILIPPINE PESO',
        value: 0.6675,
        flag: '🇵🇭',
        symbol: '₱',
    },
    {
        name: 'ARGENTINE PESO',
        value: 2.4416,
        flag: '🇦🇷',
        symbol: '$',
    },
    {
        name: 'CZECH KORUNA',
        value: 0.2708,
        flag: '🇨🇿',
        symbol: 'Kč',
    },
    {
        name: 'CHILEAN PESO',
        value: 9.7473,
        flag: '🇨🇱',
        symbol: '$',
    },
    {
        name: 'EGYPTIAN POUND',
        value: 0.3772,
        flag: '🇪🇬',
        symbol: '£',
    },
    {
        name: 'ICELANDIC KRONA',
        value: 1.7107,
        flag: '🇮🇸',
        symbol: 'kr',
    },
    {
        name: 'ISRAELI SHEKEL',
        value: 0.0441,
        flag: '🇮🇱',
        symbol: '₪',
    },
    {
        name: 'EMIRATI DIRHAM',
        value: 0.0447,
        flag: '🇦🇪',
        symbol: 'د.إ',
    },
    {
        name: 'KENYAN SHILLING',
        value: 1.5703,
        flag: '🇰🇪',
        symbol: 'Sh',
    },
    {
        name: 'LEBANESE POUND',
        value: 183.39,
        flag: '🇱🇧',
        symbol: 'ل.ل',
    },
    {
        name: 'MOROCCAN DIRHAM',
        value: 0.1265,
        flag: '🇲🇦',
        symbol: 'د.م.',
    },
    {
        name: 'PAKISTANI RUPEE',
        value: 3.3925,
        flag: '🇵🇰',
        symbol: '₨',
    },
    {
        name: 'SAUDI ARABIAN RIYAL',
        value: 0.0456,
        flag: '🇸🇦',
        symbol: '﷼',
    },
    {
        name: 'SRI LANKA RUPEE',
        value: 3.9021,
        flag: '🇱🇰',
        symbol: 'Rs',
    },
    {
        name: 'HUNGARIAN FORINT',
        value: 4.426,
        flag: '🇭🇺',
        symbol: 'Ft',
    },
    {
        name: 'CFA BEAC FRANC',
        value: 7.4796,
        flag: '🇨🇲',
        symbol: 'FCFA',
    },
    {
        name: 'CFA BCEAO FRANC',
        value: 7.4796,
        flag: '🇸🇳',
        symbol: 'CFA',
    },
    {
        name: 'JAMAICAN DOLLAR',
        value: 1.8857,
        flag: '🇯🇲',
        symbol: 'J$',
    },
    {
        name: 'NAMIBIAN DOLLAR',
        value: 0.2208,
        flag: '🇳🇦',
        symbol: 'N$',
    },
    {
        name: 'NEPALESE RUPEE',
        value: 1.5942,
        flag: '🇳🇵',
        symbol: 'रू',
    },
    {
        name: 'BANGLADESHI TAKA',
        value: 1.4076771,
        flag: '🇧🇩',
        symbol: '৳',
    }
];
